packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.22.59
  "@platforma-sdk/ui-vue": ^1.22.59
  "@platforma-sdk/workflow-tengo": ^2.13.1
  "@platforma-sdk/block-tools": ^2.5.14
  "@platforma-sdk/test": ^1.22.60
  "@platforma-sdk/tengo-builder": ^1.17.7
  "@platforma-sdk/package-builder": ^2.15.0
  "@milaboratories/graph-maker": ^1.1.48
  "@milaboratories/software-pframes-conv": ^2.1.12
  "@platforma-open/milaboratories.software-small-binaries": ^1.15.12
  "@platforma-open/milaboratories.software-cellranger": ^1.0.2
  "@platforma-open/milaboratories.cellranger-genome-assets": ^1.0.3

  "@platforma-open/milaboratories.runenv-python-3": ^1.0.0

  '@milaboratories/helpers': ^1.6.11

  'ag-grid-enterprise': &ag-grid ^33.1.1
  'ag-grid-vue3': *ag-grid
  "vue": ^3.5.13
  "vue-tsc": ^2.2.0
  "typescript": ^5.7.2
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^6.0.7
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.28.1
