packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.42.25
  "@platforma-sdk/ui-vue": ^1.42.24
  "@platforma-sdk/workflow-tengo": ^5.0.3
  "@platforma-sdk/block-tools": ^2.5.83
  "@platforma-sdk/test": ^1.42.20
  "@platforma-sdk/tengo-builder": ^2.1.16
  "@platforma-sdk/package-builder": ^2.17.2
  "@milaboratories/graph-maker": ^1.1.133

  "@milaboratories/software-pframes-conv": ^2.2.2
  '@platforma-sdk/eslint-config': ^1.0.3
  
  "@platforma-open/milaboratories.software-small-binaries": ^1.15.21
  "@platforma-open/milaboratories.software-cellranger": ^1.0.2
  "@platforma-open/milaboratories.cellranger-genome-assets": ^1.0.3
  '@platforma-open/milaboratories.gene-annotations-assets': ^1.0.0

  "@platforma-open/milaboratories.runenv-python-3": ^1.3.0

  '@milaboratories/helpers': ^1.6.21

  'ag-grid-enterprise': &ag-grid ^34.0.2
  'ag-grid-vue3': *ag-grid
  "vue": ^3.5.15
  "vue-tsc": ^2.2.10
  "typescript": ~5.6.3
  "tsup": ~8.1.2
  "turbo": ^2.5.5

  "vite": ^6.3.5
  "vitest": ~2.1.9
  "@vitejs/plugin-vue": ^5.2.4
  "@vue/tsconfig": "0.5.1"

  "@changesets/cli": ^2.29.5
