packages:
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.21.20
  "@platforma-sdk/ui-vue": ^1.21.23
  "@platforma-sdk/workflow-tengo": ^2.9.6
  "@platforma-sdk/block-tools": ^2.5.3
  "@platforma-sdk/test": ^1.21.22
  "@platforma-sdk/tengo-builder": ^1.17.5
  "@platforma-sdk/package-builder": ^2.15.0
  "@milaboratories/graph-maker": ^1.1.21
  "@milaboratories/software-pframes-conv": ^2.1.5
  "@platforma-open/milaboratories.software-small-binaries": ^1.15.6

  "@platforma-open/milaboratories.runenv-python-3": ^1.0.0

  '@milaboratories/helpers': ^1.6.11

  'ag-grid-enterprise': &ag-grid ^33.0.3
  'ag-grid-vue3': *ag-grid
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.0
  
  "typescript": ^5.7.2
  "tsup": ~8.3.5
  "turbo": ^2.3.3

  "vite": ^6.0.7
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.27.11
