packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.45.30
  "@platforma-sdk/ui-vue": ^1.45.34
  "@platforma-sdk/workflow-tengo": ^5.6.1
  "@platforma-sdk/block-tools": ^2.6.22
  "@platforma-sdk/test": ^1.45.33
  "@platforma-sdk/tengo-builder": ^2.3.9
  "@platforma-sdk/package-builder": ^3.10.7
  "@milaboratories/graph-maker": ^1.1.180
  "@platforma-sdk/blocks-deps-updater": ^2.0.0

  '@platforma-sdk/eslint-config': ^1.1.0
  
  "@platforma-open/milaboratories.software-cellranger": ^1.0.5
  "@platforma-open/milaboratories.cellranger-genome-assets": ^1.1.0
  '@platforma-open/milaboratories.gene-annotations-assets': ^1.1.0

  "@platforma-open/milaboratories.runenv-python-3": ^1.4.4

  'ag-grid-enterprise': &ag-grid ~34.1.2
  'ag-grid-vue3': *ag-grid
  "vue": ^3.5.15
  "vue-tsc": ^2.2.10
  "typescript": ~5.6.3
  "tsup": ~8.1.2
  "turbo": ^2.6.1

  "vite": ^6.3.5
  "vitest": ~2.1.9
  "@vitejs/plugin-vue": ^5.2.4
  "@vue/tsconfig": "0.5.1"
  "@vueuse/core": ^13.9.0

  "@changesets/cli": ^2.29.7
